### PR TITLE
Adds a new feature to configure Proxy in windows host

### PR DESCRIPTION
**Pull request by paulomariano77**
## Description
The paper main of this pull request is add a new feature to configure Proxy in Windows Host

## Motivation and Context
Adds support to configure Proxy in Windows hosts

## How Has This Been Tested?
This is was tested using molecule, vagrant and testinfra

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by douglasquintanilha** [comment]
@iblackman ou @bcdonadio Conseguem avaliar esse PR ?  Essa feature é importante na role da common-windows

**Review by phcaguiar — DISMISSED** [review]

**Review by bcdonadio — CHANGES_REQUESTED** [review]
This PR introduces multiple logical changes to the role. Won't be merged in the current state.

Please, remove all changes not related to Windows support and resubmit them separately.

**Comment by csmartins** [comment]
People, for how long will this shit continue to go on?? For how long I will have to point to a specific branch to use this role in Windows machines?

@paulomariano77 if you're out of time to remove all changes not related to Windows support, please address this task to someone that will.

@bcdonadio If you were so sentimental about the not related to Windows support changes, can you at least point to the commits that should not be in this PR?

You guys have untill friday to solve this issue or I myself will merge this PR, since people are already using it and it's functional. I believe that we have more important problems to care about than what commits are in or out a pull request

**Comment by bcdonadio** [comment]
I may squash the commits since there was a lot of mind change going on during the development of this PR.

However, I won't accept the need to preinstall a dependency manually on Windows to run a simple role like this. Either make the role solve this issue and install the package or have it set the system proxy another way.

**Comment by bcdonadio** [comment]
@paulomariano77 For this PR to be merged, the following list of issues need to be fixed:

* The role must install the `xNetworking` DSC Resource and be idempotent.
* The PR must only introduce changes directly related to Windows support and appropriate testing of it.
* The PR must not add any editor/linting metadata files.
* The PR must not break existing user interface (aka do not rename any user-exposed variable like you did with `proxy_whitelist`).
* Files without useful content, like `molecule/windows/tests/test_default.py` must not be present.
* The english must improve a little, though I'm available to help you with that.

If you have any questions, please reach out to me.

**Pull request closed without merging**
